package db;
// Generated 2013-9-19 19:58:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Information generated by hbm2java
 */
public class Information  implements java.io.Serializable {


     private String sno;
     private String name;
     private String password;
     private Double amount;
     private String address;
     private String birthday;
     private String school;
     private String phone;
     private String sex;
     private String grade;
     private Integer age;
     private Set<Peopleaction> peopleactions = new HashSet<Peopleaction>(0);
     private Set<Message> messages = new HashSet<Message>(0);

    public Information() {
    }

	
    public Information(String sno, String name, String password) {
        this.sno = sno;
        this.name = name;
        this.password = password;
    }
    public Information(String sno, String name, String password, Double amount, String address, String birthday, String school, String phone, String sex, String grade, Integer age, Set<Peopleaction> peopleactions, Set<Message> messages) {
       this.sno = sno;
       this.name = name;
       this.password = password;
       this.amount = amount;
       this.address = address;
       this.birthday = birthday;
       this.school = school;
       this.phone = phone;
       this.sex = sex;
       this.grade = grade;
       this.age = age;
       this.peopleactions = peopleactions;
       this.messages = messages;
    }
   
    public String getSno() {
        return this.sno;
    }
    
    public void setSno(String sno) {
        this.sno = sno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Set<Peopleaction> getPeopleactions() {
        return this.peopleactions;
    }
    
    public void setPeopleactions(Set<Peopleaction> peopleactions) {
        this.peopleactions = peopleactions;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }




}


