package db;
// Generated 2013-9-19 19:58:32 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private Information information;
     private String title;
     private String context;
     private Date time;

    public Message() {
    }

    public Message(Information information, String title, String context, Date time) {
       this.information = information;
       this.title = title;
       this.context = context;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Information getInformation() {
        return this.information;
    }
    
    public void setInformation(Information information) {
        this.information = information;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public Date getTime() {
        return this.time;
    }
    
    public String getFormatTime(){
        SimpleDateFormat myFormat = new SimpleDateFormat("HH:mm yyyy/M/d"); 
        return myFormat.format(this.time);
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


