package db;
// Generated 2013-9-19 19:58:32 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Peopleaction generated by hbm2java
 */
public class Peopleaction  implements java.io.Serializable {


     private Integer id;
     private Window window;
     private Information information;
     private Dishes dishes;
     private int initrice;
     private int restrice;
     private int score;
     private Date time;

    public Peopleaction() {
    }

    public Peopleaction(Window window, Information information, Dishes dishes, int initrice, int restrice, int score, Date time) {
       this.window = window;
       this.information = information;
       this.dishes = dishes;
       this.initrice = initrice;
       this.restrice = restrice;
       this.score = score;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Window getWindow() {
        return this.window;
    }
    
    public void setWindow(Window window) {
        this.window = window;
    }
    public Information getInformation() {
        return this.information;
    }
    
    public void setInformation(Information information) {
        this.information = information;
    }
    public Dishes getDishes() {
        return this.dishes;
    }
    
    public void setDishes(Dishes dishes) {
        this.dishes = dishes;
    }
    public int getInitrice() {
        return this.initrice;
    }
    
    public void setInitrice(int initrice) {
        this.initrice = initrice;
    }
    public int getRestrice() {
        return this.restrice;
    }
    
    public void setRestrice(int restrice) {
        this.restrice = restrice;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    public String getFormatTime(){
        SimpleDateFormat myFormat = new SimpleDateFormat("HH:mm yyyy/M/d"); 
        return myFormat.format(this.time);
    }


}


