package db;
// Generated 2013-9-19 19:58:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Window generated by hbm2java
 */
public class Window  implements java.io.Serializable {


     private String cno;
     private String cname;
     private String picture;
     private Set<Peopleaction> peopleactions = new HashSet<Peopleaction>(0);
     private Set<Dishes> disheses = new HashSet<Dishes>(0);

    public Window() {
    }

	
    public Window(String cno, String cname) {
        this.cno = cno;
        this.cname = cname;
    }
    public Window(String cno, String cname, String picture, Set<Peopleaction> peopleactions, Set<Dishes> disheses) {
       this.cno = cno;
       this.cname = cname;
       this.picture = picture;
       this.peopleactions = peopleactions;
       this.disheses = disheses;
    }
   
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Set<Peopleaction> getPeopleactions() {
        return this.peopleactions;
    }
    
    public void setPeopleactions(Set<Peopleaction> peopleactions) {
        this.peopleactions = peopleactions;
    }
    public Set<Dishes> getDisheses() {
        return this.disheses;
    }
    
    public void setDisheses(Set<Dishes> disheses) {
        this.disheses = disheses;
    }




}


